declare module 'react-native-tailwindcss' {
  export interface TailwindColors {
    transparent: 'rgba(0,0,0,0)';
    black: '#000';
    white: '#fff';
    gray100: '#eee';
    gray200: '#ebebeb';
    gray300: '#ececec';
    gray400: '#ccc';
    gray500: '#999';
    gray600: '#777';
    gray700: '#555';
    gray800: '#1a1a1a';
    gray900: '#111';
    blueLighter: '#99ffff';
    blueLight: '#99ccff';
    blue: 'blue';
    green: '#00cc66';
    orange: '#ff9900';
    pink: '#ff9999';
    pinkIntense: '#ff00cc';
    purple: '#6633cc';
    redLighter: '#ff3366';
    redLight: '#ff0066';
    red: '#ff0033';
    tealLight: '#99ff99';
    teal: '#00ffcc';
    yellow: '#ffce33';
  }
  export interface TailwindStyles {
    contentStart: { alignContent: 'flex-start' };
    contentEnd: { alignContent: 'flex-end' };
    contentCenter: { alignContent: 'center' };
    contentStretch: { alignContent: 'stretch' };
    contentBetween: { alignContent: 'space-between' };
    contentAround: { alignContent: 'space-around' };
    itemsStart: { alignItems: 'flex-start' };
    itemsEnd: { alignItems: 'flex-end' };
    itemsCenter: { alignItems: 'center' };
    itemsStretch: { alignItems: 'stretch' };
    itemsBaseline: { alignItems: 'baseline' };
    selfAuto: { alignSelf: 'auto' };
    selfStart: { alignSelf: 'flex-start' };
    selfEnd: { alignSelf: 'flex-end' };
    selfCenter: { alignSelf: 'center' };
    selfStretch: { alignSelf: 'stretch' };
    selfBaseline: { alignSelf: 'baseline' };
    backfaceVisible: { backfaceVisibility: 'visible' };
    backfaceHidden: { backfaceVisibility: 'hidden' };
    borderSolid: { borderStyle: 'solid' };
    borderDotted: { borderStyle: 'dotted' };
    borderDashed: { borderStyle: 'dashed' };
    directionInherit: { direction: 'inherit' };
    directionLtr: { direction: 'ltr' };
    directionRtl: { direction: 'rtl' };
    hidden: { display: 'none' };
    flex: { display: 'flex' };
    flexRow: { flexDirection: 'row' };
    flexRowReverse: { flexDirection: 'row-reverse' };
    flexCol: { flexDirection: 'column' };
    flexColReverse: { flexDirection: 'column-reverse' };
    flexWrap: { flexWrap: 'wrap' };
    flexWrapReverse: { flexWrap: 'wrap-reverse' };
    flexNoWrap: { flexWrap: 'nowrap' };
    fontPadding: { includeFontPadding: true };
    fontPaddingFalse: { includeFontPadding: false };
    notItalic: { fontStyle: 'normal' };
    italic: { fontStyle: 'italic' };
    fontNormal: { fontWeight: 'normal' };
    fontBold: { fontWeight: 'bold' };
    fontHairline: { fontWeight: '100' };
    fontThin: { fontWeight: '200' };
    fontLight: { fontWeight: '300' };
    fontMedium: { fontWeight: '500' };
    fontSemibold: { fontWeight: '600' };
    fontExtrabold: { fontWeight: '800' };
    fontBlack: { fontWeight: '900' };
    justifyStart: { justifyContent: 'flex-start' };
    justifyEnd: { justifyContent: 'flex-end' };
    justifyCenter: { justifyContent: 'center' };
    justifyBetween: { justifyContent: 'space-between' };
    justifyAround: { justifyContent: 'space-around' };
    justifyEvenly: { justifyContent: 'space-evenly' };
    objectContain: { resizeMode: 'contain' };
    objectCover: { resizeMode: 'cover' };
    objectStretch: { resizeMode: 'stretch' };
    objectCenter: { resizeMode: 'center' };
    objectRepeat: { resizeMode: 'repeat' };
    overflowVisible: { overflow: 'visible' };
    overflowHidden: { overflow: 'hidden' };
    absolute: { position: 'absolute' };
    relative: { position: 'relative' };
    resizeContain: { resizeMode: 'contain' };
    resizeCover: { resizeMode: 'cover' };
    resizeStretch: { resizeMode: 'stretch' };
    resizeCenter: { resizeMode: 'center' };
    resizeRepeat: { resizeMode: 'repeat' };
    textAuto: { textAlign: 'auto' };
    textLeft: { textAlign: 'left' };
    textRight: { textAlign: 'right' };
    textCenter: { textAlign: 'center' };
    textJustify: { textAlign: 'justify' };
    noUnderline: { textDecorationLine: 'none' };
    underline: { textDecorationLine: 'underline' };
    lineThrough: { textDecorationLine: 'line-through' };
    underlineLineThrough: { textDecorationLine: 'underline line-through' };
    normalCase: { textTransform: 'none' };
    uppercase: { textTransform: 'uppercase' };
    lowercase: { textTransform: 'lowercase' };
    capitalize: { textTransform: 'capitalize' };
    alignAuto: { textAlignVertical: 'auto' };
    alignTop: { textAlignVertical: 'top' };
    alignBottom: { textAlignVertical: 'bottom' };
    alignCenter: { textAlignVertical: 'center' };
    bgTransparent: { backgroundColor: 'rgba(0,0,0,0)' };
    bgBlack: { backgroundColor: '#000' };
    bgWhite: { backgroundColor: '#fff' };
    bgGray100: { backgroundColor: '#eee' };
    bgGray200: { backgroundColor: '#ebebeb' };
    bgGray300: { backgroundColor: '#ececec' };
    bgGray400: { backgroundColor: '#ccc' };
    bgGray500: { backgroundColor: '#999' };
    bgGray600: { backgroundColor: '#777' };
    bgGray700: { backgroundColor: '#555' };
    bgGray800: { backgroundColor: '#1a1a1a' };
    bgGray900: { backgroundColor: '#111' };
    bgBlueLighter: { backgroundColor: '#99ffff' };
    bgBlueLight: { backgroundColor: '#99ccff' };
    bgBlue: { backgroundColor: 'blue' };
    bgGreen: { backgroundColor: '#00cc66' };
    bgOrange: { backgroundColor: '#ff9900' };
    bgPink: { backgroundColor: '#ff9999' };
    bgPinkIntense: { backgroundColor: '#ff00cc' };
    bgPurple: { backgroundColor: '#6633cc' };
    bgRedLighter: { backgroundColor: '#ff3366' };
    bgRedLight: { backgroundColor: '#ff0066' };
    bgRed: { backgroundColor: '#ff0033' };
    bgTealLight: { backgroundColor: '#99ff99' };
    bgTeal: { backgroundColor: '#00ffcc' };
    bgYellow: { backgroundColor: '#ffce33' };
    borderTransparent: { borderColor: 'rgba(0,0,0,0)' };
    borderBlack: { borderColor: '#000' };
    borderWhite: { borderColor: '#fff' };
    borderGray100: { borderColor: '#eee' };
    borderGray200: { borderColor: '#ebebeb' };
    borderGray300: { borderColor: '#ececec' };
    borderGray400: { borderColor: '#ccc' };
    borderGray500: { borderColor: '#999' };
    borderGray600: { borderColor: '#777' };
    borderGray700: { borderColor: '#555' };
    borderGray800: { borderColor: '#1a1a1a' };
    borderGray900: { borderColor: '#111' };
    borderBlueLighter: { borderColor: '#99ffff' };
    borderBlueLight: { borderColor: '#99ccff' };
    borderBlue: { borderColor: 'blue' };
    borderGreen: { borderColor: '#00cc66' };
    borderOrange: { borderColor: '#ff9900' };
    borderPink: { borderColor: '#ff9999' };
    borderPinkIntense: { borderColor: '#ff00cc' };
    borderPurple: { borderColor: '#6633cc' };
    borderRedLighter: { borderColor: '#ff3366' };
    borderRedLight: { borderColor: '#ff0066' };
    borderRed: { borderColor: '#ff0033' };
    borderTealLight: { borderColor: '#99ff99' };
    borderTeal: { borderColor: '#00ffcc' };
    borderYellow: { borderColor: '#ffce33' };
    roundedNone: { borderRadius: 0 };
    roundedSm: { borderRadius: 2 };
    rounded: { borderRadius: 4 };
    roundedLg: { borderRadius: 8 };
    roundedFull: { borderRadius: 9999 };
    roundedTNone: { borderTopLeftRadius: 0; borderTopRightRadius: 0 };
    roundedTSm: { borderTopLeftRadius: 2; borderTopRightRadius: 2 };
    roundedT: { borderTopLeftRadius: 4; borderTopRightRadius: 4 };
    roundedTLg: { borderTopLeftRadius: 8; borderTopRightRadius: 8 };
    roundedTFull: { borderTopLeftRadius: 9999; borderTopRightRadius: 9999 };
    roundedRNone: { borderTopRightRadius: 0; borderBottomRightRadius: 0 };
    roundedRSm: { borderTopRightRadius: 2; borderBottomRightRadius: 2 };
    roundedR: { borderTopRightRadius: 4; borderBottomRightRadius: 4 };
    roundedRLg: { borderTopRightRadius: 8; borderBottomRightRadius: 8 };
    roundedRFull: { borderTopRightRadius: 9999; borderBottomRightRadius: 9999 };
    roundedBNone: { borderBottomLeftRadius: 0; borderBottomRightRadius: 0 };
    roundedBSm: { borderBottomLeftRadius: 2; borderBottomRightRadius: 2 };
    roundedB: { borderBottomLeftRadius: 4; borderBottomRightRadius: 4 };
    roundedBLg: { borderBottomLeftRadius: 8; borderBottomRightRadius: 8 };
    roundedBFull: { borderBottomLeftRadius: 9999; borderBottomRightRadius: 9999 };
    roundedLNone: { borderTopLeftRadius: 0; borderBottomLeftRadius: 0 };
    roundedLSm: { borderTopLeftRadius: 2; borderBottomLeftRadius: 2 };
    roundedL: { borderTopLeftRadius: 4; borderBottomLeftRadius: 4 };
    roundedLLg: { borderTopLeftRadius: 8; borderBottomLeftRadius: 8 };
    roundedLFull: { borderTopLeftRadius: 9999; borderBottomLeftRadius: 9999 };
    roundedTlNone: { borderTopLeftRadius: 0 };
    roundedTlSm: { borderTopLeftRadius: 2 };
    roundedTl: { borderTopLeftRadius: 4 };
    roundedTlLg: { borderTopLeftRadius: 8 };
    roundedTlFull: { borderTopLeftRadius: 9999 };
    roundedTrNone: { borderTopRightRadius: 0 };
    roundedTrSm: { borderTopRightRadius: 2 };
    roundedTr: { borderTopRightRadius: 4 };
    roundedTrLg: { borderTopRightRadius: 8 };
    roundedTrFull: { borderTopRightRadius: 9999 };
    roundedBrNone: { borderBottomRightRadius: 0 };
    roundedBrSm: { borderBottomRightRadius: 2 };
    roundedBr: { borderBottomRightRadius: 4 };
    roundedBrLg: { borderBottomRightRadius: 8 };
    roundedBrFull: { borderBottomRightRadius: 9999 };
    roundedBlNone: { borderBottomLeftRadius: 0 };
    roundedBlSm: { borderBottomLeftRadius: 2 };
    roundedBl: { borderBottomLeftRadius: 4 };
    roundedBlLg: { borderBottomLeftRadius: 8 };
    roundedBlFull: { borderBottomLeftRadius: 9999 };
    roundedENone: { borderTopEndRadius: 0; borderBottomEndRadius: 0 };
    roundedESm: { borderTopEndRadius: 2; borderBottomEndRadius: 2 };
    roundedE: { borderTopEndRadius: 4; borderBottomEndRadius: 4 };
    roundedELg: { borderTopEndRadius: 8; borderBottomEndRadius: 8 };
    roundedEFull: { borderTopEndRadius: 9999; borderBottomEndRadius: 9999 };
    roundedSNone: { borderTopStartRadius: 0; borderBottomStartRadius: 0 };
    roundedSSm: { borderTopStartRadius: 2; borderBottomStartRadius: 2 };
    roundedS: { borderTopStartRadius: 4; borderBottomStartRadius: 4 };
    roundedSLg: { borderTopStartRadius: 8; borderBottomStartRadius: 8 };
    roundedSFull: { borderTopStartRadius: 9999; borderBottomStartRadius: 9999 };
    roundedTsNone: { borderTopStartRadius: 0 };
    roundedTsSm: { borderTopStartRadius: 2 };
    roundedTs: { borderTopStartRadius: 4 };
    roundedTsLg: { borderTopStartRadius: 8 };
    roundedTsFull: { borderTopStartRadius: 9999 };
    roundedTeNone: { borderTopEndRadius: 0 };
    roundedTeSm: { borderTopEndRadius: 2 };
    roundedTe: { borderTopEndRadius: 4 };
    roundedTeLg: { borderTopEndRadius: 8 };
    roundedTeFull: { borderTopEndRadius: 9999 };
    roundedBeNone: { borderBottomEndRadius: 0 };
    roundedBeSm: { borderBottomEndRadius: 2 };
    roundedBe: { borderBottomEndRadius: 4 };
    roundedBeLg: { borderBottomEndRadius: 8 };
    roundedBeFull: { borderBottomEndRadius: 9999 };
    roundedBsNone: { borderBottomStartRadius: 0 };
    roundedBsSm: { borderBottomStartRadius: 2 };
    roundedBs: { borderBottomStartRadius: 4 };
    roundedBsLg: { borderBottomStartRadius: 8 };
    roundedBsFull: { borderBottomStartRadius: 9999 };
    border0: { borderWidth: 0 };
    border2: { borderWidth: 2 };
    border4: { borderWidth: 4 };
    border8: { borderWidth: 8 };
    border: { borderWidth: 1 };
    borderX0: { borderRightWidth: 0; borderLeftWidth: 0 };
    borderX2: { borderRightWidth: 2; borderLeftWidth: 2 };
    borderX4: { borderRightWidth: 4; borderLeftWidth: 4 };
    borderX8: { borderRightWidth: 8; borderLeftWidth: 8 };
    borderX: { borderRightWidth: 1; borderLeftWidth: 1 };
    borderY0: { borderTopWidth: 0; borderBottomWidth: 0 };
    borderY2: { borderTopWidth: 2; borderBottomWidth: 2 };
    borderY4: { borderTopWidth: 4; borderBottomWidth: 4 };
    borderY8: { borderTopWidth: 8; borderBottomWidth: 8 };
    borderY: { borderTopWidth: 1; borderBottomWidth: 1 };
    borderT0: { borderTopWidth: 0 };
    borderT2: { borderTopWidth: 2 };
    borderT4: { borderTopWidth: 4 };
    borderT8: { borderTopWidth: 8 };
    borderT: { borderTopWidth: 1 };
    borderR0: { borderRightWidth: 0 };
    borderR2: { borderRightWidth: 2 };
    borderR4: { borderRightWidth: 4 };
    borderR8: { borderRightWidth: 8 };
    borderR: { borderRightWidth: 1 };
    borderB0: { borderBottomWidth: 0 };
    borderB2: { borderBottomWidth: 2 };
    borderB4: { borderBottomWidth: 4 };
    borderB8: { borderBottomWidth: 8 };
    borderB: { borderBottomWidth: 1 };
    borderL0: { borderLeftWidth: 0 };
    borderL2: { borderLeftWidth: 2 };
    borderL4: { borderLeftWidth: 4 };
    borderL8: { borderLeftWidth: 8 };
    borderL: { borderLeftWidth: 1 };
    borderE0: { borderEndWidth: 0 };
    borderE2: { borderEndWidth: 2 };
    borderE4: { borderEndWidth: 4 };
    borderE8: { borderEndWidth: 8 };
    borderE: { borderEndWidth: 1 };
    borderS0: { borderStartWidth: 0 };
    borderS2: { borderStartWidth: 2 };
    borderS4: { borderStartWidth: 4 };
    borderS8: { borderStartWidth: 8 };
    borderS: { borderStartWidth: 1 };
    flex1: { flex: 1 };
    flexAuto: { flex: 1 };
    flexInitial: { flex: 0 };
    flexNone: { flex: 0 };
    flexGrow0: { flexGrow: 0 };
    flexGrow: { flexGrow: 1 };
    flexShrink0: { flexShrink: 0 };
    flexShrink: { flexShrink: 1 };
    fontSans: { fontFamily: '-apple-system' };
    fontSerif: { fontFamily: 'Georgia' };
    fontMono: { fontFamily: 'Menlo' };
    textXs: { fontSize: 12 };
    textSm: { fontSize: 14 };
    textBase: { fontSize: 16 };
    textLg: { fontSize: 18 };
    textXl: { fontSize: 20 };
    text2xl: { fontSize: 24 };
    text3xl: { fontSize: 30 };
    text4xl: { fontSize: 36 };
    text5xl: { fontSize: 48 };
    text6xl: { fontSize: 64 };
    h0: { height: 0 };
    h1: { height: 4 };
    h2: { height: 8 };
    h3: { height: 12 };
    h4: { height: 16 };
    h5: { height: 20 };
    h6: { height: 24 };
    h8: { height: 32 };
    h10: { height: 40 };
    h12: { height: 48 };
    h16: { height: 64 };
    h20: { height: 80 };
    h24: { height: 96 };
    h32: { height: 128 };
    h40: { height: 160 };
    h48: { height: 192 };
    h56: { height: 224 };
    h64: { height: 256 };
    hAuto: { height: 'auto' };
    hPx: { height: 1 };
    hFull: { height: '100%' };
    hScreen: { height: '100vh' };
    inset0: { top: 0; bottom: 0; left: 0; right: 0 };
    insetAuto: { top: 'auto'; bottom: 'auto'; left: 'auto'; right: 'auto' };
    insetX0: { left: 0; right: 0 };
    insetXAuto: { left: 'auto'; right: 'auto' };
    insetY0: { top: 0; bottom: 0 };
    insetYAuto: { top: 'auto'; bottom: 'auto' };
    top0: { top: 0 };
    topAuto: { top: 'auto' };
    bottom0: { bottom: 0 };
    bottomAuto: { bottom: 'auto' };
    left0: { left: 0 };
    leftAuto: { left: 'auto' };
    right0: { right: 0 };
    rightAuto: { right: 'auto' };
    start0: { start: 0 };
    startAuto: { start: 'auto' };
    end0: { end: 0 };
    endAuto: { end: 'auto' };
    trackingTighter: { letterSpacing: -0.8 };
    trackingTight: { letterSpacing: -0.4 };
    trackingNormal: { letterSpacing: 0 };
    trackingWide: { letterSpacing: 0.4 };
    trackingWider: { letterSpacing: 0.8 };
    trackingWidest: { letterSpacing: 1.6 };
    leadingNone: { lineHeight: 1 };
    leadingTight: { lineHeight: 1.25 };
    leadingSnug: { lineHeight: 1.375 };
    leadingNormal: { lineHeight: 1.5 };
    leadingRelaxed: { lineHeight: 1.625 };
    leadingLoose: { lineHeight: 2 };
    m0: { margin: 0 };
    m1: { margin: 4 };
    m2: { margin: 8 };
    m3: { margin: 12 };
    m4: { margin: 16 };
    m5: { margin: 20 };
    m6: { margin: 24 };
    m8: { margin: 32 };
    m10: { margin: 40 };
    m12: { margin: 48 };
    m16: { margin: 64 };
    m20: { margin: 80 };
    m24: { margin: 96 };
    m32: { margin: 128 };
    m40: { margin: 160 };
    m48: { margin: 192 };
    m56: { margin: 224 };
    m64: { margin: 256 };
    mAuto: { margin: 'auto' };
    mPx: { margin: 1 };
    _m1: { margin: -4 };
    _m2: { margin: -8 };
    _m3: { margin: -12 };
    _m4: { margin: -16 };
    _m5: { margin: -20 };
    _m6: { margin: -24 };
    _m8: { margin: -32 };
    _m10: { margin: -40 };
    _m12: { margin: -48 };
    _m16: { margin: -64 };
    _m20: { margin: -80 };
    _m24: { margin: -96 };
    _m32: { margin: -128 };
    _m40: { margin: -160 };
    _m48: { margin: -192 };
    _m56: { margin: -224 };
    _m64: { margin: -256 };
    _mPx: { margin: -1 };
    mX0: { marginHorizontal: 0 };
    mX1: { marginHorizontal: 4 };
    mX2: { marginHorizontal: 8 };
    mX3: { marginHorizontal: 12 };
    mX4: { marginHorizontal: 16 };
    mX5: { marginHorizontal: 20 };
    mX6: { marginHorizontal: 24 };
    mX8: { marginHorizontal: 32 };
    mX10: { marginHorizontal: 40 };
    mX12: { marginHorizontal: 48 };
    mX16: { marginHorizontal: 64 };
    mX20: { marginHorizontal: 80 };
    mX24: { marginHorizontal: 96 };
    mX32: { marginHorizontal: 128 };
    mX40: { marginHorizontal: 160 };
    mX48: { marginHorizontal: 192 };
    mX56: { marginHorizontal: 224 };
    mX64: { marginHorizontal: 256 };
    mXAuto: { marginHorizontal: 'auto' };
    mXPx: { marginHorizontal: 1 };
    _mX1: { marginHorizontal: -4 };
    _mX2: { marginHorizontal: -8 };
    _mX3: { marginHorizontal: -12 };
    _mX4: { marginHorizontal: -16 };
    _mX5: { marginHorizontal: -20 };
    _mX6: { marginHorizontal: -24 };
    _mX8: { marginHorizontal: -32 };
    _mX10: { marginHorizontal: -40 };
    _mX12: { marginHorizontal: -48 };
    _mX16: { marginHorizontal: -64 };
    _mX20: { marginHorizontal: -80 };
    _mX24: { marginHorizontal: -96 };
    _mX32: { marginHorizontal: -128 };
    _mX40: { marginHorizontal: -160 };
    _mX48: { marginHorizontal: -192 };
    _mX56: { marginHorizontal: -224 };
    _mX64: { marginHorizontal: -256 };
    _mXPx: { marginHorizontal: -1 };
    mY0: { marginVertical: 0 };
    mY1: { marginVertical: 4 };
    mY2: { marginVertical: 8 };
    mY3: { marginVertical: 12 };
    mY4: { marginVertical: 16 };
    mY5: { marginVertical: 20 };
    mY6: { marginVertical: 24 };
    mY8: { marginVertical: 32 };
    mY10: { marginVertical: 40 };
    mY12: { marginVertical: 48 };
    mY16: { marginVertical: 64 };
    mY20: { marginVertical: 80 };
    mY24: { marginVertical: 96 };
    mY32: { marginVertical: 128 };
    mY40: { marginVertical: 160 };
    mY48: { marginVertical: 192 };
    mY56: { marginVertical: 224 };
    mY64: { marginVertical: 256 };
    mYAuto: { marginVertical: 'auto' };
    mYPx: { marginVertical: 1 };
    _mY1: { marginVertical: -4 };
    _mY2: { marginVertical: -8 };
    _mY3: { marginVertical: -12 };
    _mY4: { marginVertical: -16 };
    _mY5: { marginVertical: -20 };
    _mY6: { marginVertical: -24 };
    _mY8: { marginVertical: -32 };
    _mY10: { marginVertical: -40 };
    _mY12: { marginVertical: -48 };
    _mY16: { marginVertical: -64 };
    _mY20: { marginVertical: -80 };
    _mY24: { marginVertical: -96 };
    _mY32: { marginVertical: -128 };
    _mY40: { marginVertical: -160 };
    _mY48: { marginVertical: -192 };
    _mY56: { marginVertical: -224 };
    _mY64: { marginVertical: -256 };
    _mYPx: { marginVertical: -1 };
    mT0: { marginTop: 0 };
    mT1: { marginTop: 4 };
    mT2: { marginTop: 8 };
    mT3: { marginTop: 12 };
    mT4: { marginTop: 16 };
    mT5: { marginTop: 20 };
    mT6: { marginTop: 24 };
    mT8: { marginTop: 32 };
    mT10: { marginTop: 40 };
    mT12: { marginTop: 48 };
    mT16: { marginTop: 64 };
    mT20: { marginTop: 80 };
    mT24: { marginTop: 96 };
    mT32: { marginTop: 128 };
    mT40: { marginTop: 160 };
    mT48: { marginTop: 192 };
    mT56: { marginTop: 224 };
    mT64: { marginTop: 256 };
    mTAuto: { marginTop: 'auto' };
    mTPx: { marginTop: 1 };
    _mT1: { marginTop: -4 };
    _mT2: { marginTop: -8 };
    _mT3: { marginTop: -12 };
    _mT4: { marginTop: -16 };
    _mT5: { marginTop: -20 };
    _mT6: { marginTop: -24 };
    _mT8: { marginTop: -32 };
    _mT10: { marginTop: -40 };
    _mT12: { marginTop: -48 };
    _mT16: { marginTop: -64 };
    _mT20: { marginTop: -80 };
    _mT24: { marginTop: -96 };
    _mT32: { marginTop: -128 };
    _mT40: { marginTop: -160 };
    _mT48: { marginTop: -192 };
    _mT56: { marginTop: -224 };
    _mT64: { marginTop: -256 };
    _mTPx: { marginTop: -1 };
    mR0: { marginRight: 0 };
    mR1: { marginRight: 4 };
    mR2: { marginRight: 8 };
    mR3: { marginRight: 12 };
    mR4: { marginRight: 16 };
    mR5: { marginRight: 20 };
    mR6: { marginRight: 24 };
    mR8: { marginRight: 32 };
    mR10: { marginRight: 40 };
    mR12: { marginRight: 48 };
    mR16: { marginRight: 64 };
    mR20: { marginRight: 80 };
    mR24: { marginRight: 96 };
    mR32: { marginRight: 128 };
    mR40: { marginRight: 160 };
    mR48: { marginRight: 192 };
    mR56: { marginRight: 224 };
    mR64: { marginRight: 256 };
    mRAuto: { marginRight: 'auto' };
    mRPx: { marginRight: 1 };
    _mR1: { marginRight: -4 };
    _mR2: { marginRight: -8 };
    _mR3: { marginRight: -12 };
    _mR4: { marginRight: -16 };
    _mR5: { marginRight: -20 };
    _mR6: { marginRight: -24 };
    _mR8: { marginRight: -32 };
    _mR10: { marginRight: -40 };
    _mR12: { marginRight: -48 };
    _mR16: { marginRight: -64 };
    _mR20: { marginRight: -80 };
    _mR24: { marginRight: -96 };
    _mR32: { marginRight: -128 };
    _mR40: { marginRight: -160 };
    _mR48: { marginRight: -192 };
    _mR56: { marginRight: -224 };
    _mR64: { marginRight: -256 };
    _mRPx: { marginRight: -1 };
    mB0: { marginBottom: 0 };
    mB1: { marginBottom: 4 };
    mB2: { marginBottom: 8 };
    mB3: { marginBottom: 12 };
    mB4: { marginBottom: 16 };
    mB5: { marginBottom: 20 };
    mB6: { marginBottom: 24 };
    mB8: { marginBottom: 32 };
    mB10: { marginBottom: 40 };
    mB12: { marginBottom: 48 };
    mB16: { marginBottom: 64 };
    mB20: { marginBottom: 80 };
    mB24: { marginBottom: 96 };
    mB32: { marginBottom: 128 };
    mB40: { marginBottom: 160 };
    mB48: { marginBottom: 192 };
    mB56: { marginBottom: 224 };
    mB64: { marginBottom: 256 };
    mBAuto: { marginBottom: 'auto' };
    mBPx: { marginBottom: 1 };
    _mB1: { marginBottom: -4 };
    _mB2: { marginBottom: -8 };
    _mB3: { marginBottom: -12 };
    _mB4: { marginBottom: -16 };
    _mB5: { marginBottom: -20 };
    _mB6: { marginBottom: -24 };
    _mB8: { marginBottom: -32 };
    _mB10: { marginBottom: -40 };
    _mB12: { marginBottom: -48 };
    _mB16: { marginBottom: -64 };
    _mB20: { marginBottom: -80 };
    _mB24: { marginBottom: -96 };
    _mB32: { marginBottom: -128 };
    _mB40: { marginBottom: -160 };
    _mB48: { marginBottom: -192 };
    _mB56: { marginBottom: -224 };
    _mB64: { marginBottom: -256 };
    _mBPx: { marginBottom: -1 };
    mL0: { marginLeft: 0 };
    mL1: { marginLeft: 4 };
    mL2: { marginLeft: 8 };
    mL3: { marginLeft: 12 };
    mL4: { marginLeft: 16 };
    mL5: { marginLeft: 20 };
    mL6: { marginLeft: 24 };
    mL8: { marginLeft: 32 };
    mL10: { marginLeft: 40 };
    mL12: { marginLeft: 48 };
    mL16: { marginLeft: 64 };
    mL20: { marginLeft: 80 };
    mL24: { marginLeft: 96 };
    mL32: { marginLeft: 128 };
    mL40: { marginLeft: 160 };
    mL48: { marginLeft: 192 };
    mL56: { marginLeft: 224 };
    mL64: { marginLeft: 256 };
    mLAuto: { marginLeft: 'auto' };
    mLPx: { marginLeft: 1 };
    _mL1: { marginLeft: -4 };
    _mL2: { marginLeft: -8 };
    _mL3: { marginLeft: -12 };
    _mL4: { marginLeft: -16 };
    _mL5: { marginLeft: -20 };
    _mL6: { marginLeft: -24 };
    _mL8: { marginLeft: -32 };
    _mL10: { marginLeft: -40 };
    _mL12: { marginLeft: -48 };
    _mL16: { marginLeft: -64 };
    _mL20: { marginLeft: -80 };
    _mL24: { marginLeft: -96 };
    _mL32: { marginLeft: -128 };
    _mL40: { marginLeft: -160 };
    _mL48: { marginLeft: -192 };
    _mL56: { marginLeft: -224 };
    _mL64: { marginLeft: -256 };
    _mLPx: { marginLeft: -1 };
    mS0: { marginStart: 0 };
    mS1: { marginStart: 4 };
    mS2: { marginStart: 8 };
    mS3: { marginStart: 12 };
    mS4: { marginStart: 16 };
    mS5: { marginStart: 20 };
    mS6: { marginStart: 24 };
    mS8: { marginStart: 32 };
    mS10: { marginStart: 40 };
    mS12: { marginStart: 48 };
    mS16: { marginStart: 64 };
    mS20: { marginStart: 80 };
    mS24: { marginStart: 96 };
    mS32: { marginStart: 128 };
    mS40: { marginStart: 160 };
    mS48: { marginStart: 192 };
    mS56: { marginStart: 224 };
    mS64: { marginStart: 256 };
    mSAuto: { marginStart: 'auto' };
    mSPx: { marginStart: 1 };
    _mS1: { marginStart: -4 };
    _mS2: { marginStart: -8 };
    _mS3: { marginStart: -12 };
    _mS4: { marginStart: -16 };
    _mS5: { marginStart: -20 };
    _mS6: { marginStart: -24 };
    _mS8: { marginStart: -32 };
    _mS10: { marginStart: -40 };
    _mS12: { marginStart: -48 };
    _mS16: { marginStart: -64 };
    _mS20: { marginStart: -80 };
    _mS24: { marginStart: -96 };
    _mS32: { marginStart: -128 };
    _mS40: { marginStart: -160 };
    _mS48: { marginStart: -192 };
    _mS56: { marginStart: -224 };
    _mS64: { marginStart: -256 };
    _mSPx: { marginStart: -1 };
    mE0: { marginEnd: 0 };
    mE1: { marginEnd: 4 };
    mE2: { marginEnd: 8 };
    mE3: { marginEnd: 12 };
    mE4: { marginEnd: 16 };
    mE5: { marginEnd: 20 };
    mE6: { marginEnd: 24 };
    mE8: { marginEnd: 32 };
    mE10: { marginEnd: 40 };
    mE12: { marginEnd: 48 };
    mE16: { marginEnd: 64 };
    mE20: { marginEnd: 80 };
    mE24: { marginEnd: 96 };
    mE32: { marginEnd: 128 };
    mE40: { marginEnd: 160 };
    mE48: { marginEnd: 192 };
    mE56: { marginEnd: 224 };
    mE64: { marginEnd: 256 };
    mEAuto: { marginEnd: 'auto' };
    mEPx: { marginEnd: 1 };
    _mE1: { marginEnd: -4 };
    _mE2: { marginEnd: -8 };
    _mE3: { marginEnd: -12 };
    _mE4: { marginEnd: -16 };
    _mE5: { marginEnd: -20 };
    _mE6: { marginEnd: -24 };
    _mE8: { marginEnd: -32 };
    _mE10: { marginEnd: -40 };
    _mE12: { marginEnd: -48 };
    _mE16: { marginEnd: -64 };
    _mE20: { marginEnd: -80 };
    _mE24: { marginEnd: -96 };
    _mE32: { marginEnd: -128 };
    _mE40: { marginEnd: -160 };
    _mE48: { marginEnd: -192 };
    _mE56: { marginEnd: -224 };
    _mE64: { marginEnd: -256 };
    _mEPx: { marginEnd: -1 };
    maxHFull: { maxHeight: '100%' };
    maxHScreen: { maxHeight: '100vh' };
    maxWXs: { maxWidth: 320 };
    maxWSm: { maxWidth: 384 };
    maxWMd: { maxWidth: 448 };
    maxWLg: { maxWidth: 512 };
    maxWXl: { maxWidth: 576 };
    maxW2xl: { maxWidth: 672 };
    maxW3xl: { maxWidth: 768 };
    maxW4xl: { maxWidth: 896 };
    maxW5xl: { maxWidth: 1024 };
    maxW6xl: { maxWidth: 1152 };
    maxWFull: { maxWidth: '100%' };
    minH0: { minHeight: 0 };
    minHFull: { minHeight: '100%' };
    minHScreen: { minHeight: '100vh' };
    minW0: { minWidth: 0 };
    minWFull: { minWidth: '100%' };
    opacity0: { opacity: 0 };
    opacity25: { opacity: 0.25 };
    opacity50: { opacity: 0.5 };
    opacity75: { opacity: 0.75 };
    opacity100: { opacity: 1 };
    p0: { padding: 0 };
    p1: { padding: 4 };
    p2: { padding: 8 };
    p3: { padding: 12 };
    p4: { padding: 16 };
    p5: { padding: 20 };
    p6: { padding: 24 };
    p8: { padding: 32 };
    p10: { padding: 40 };
    p12: { padding: 48 };
    p16: { padding: 64 };
    p20: { padding: 80 };
    p24: { padding: 96 };
    p32: { padding: 128 };
    p40: { padding: 160 };
    p48: { padding: 192 };
    p56: { padding: 224 };
    p64: { padding: 256 };
    pPx: { padding: 1 };
    pX0: { paddingHorizontal: 0 };
    pX1: { paddingHorizontal: 4 };
    pX2: { paddingHorizontal: 8 };
    pX3: { paddingHorizontal: 12 };
    pX4: { paddingHorizontal: 16 };
    pX5: { paddingHorizontal: 20 };
    pX6: { paddingHorizontal: 24 };
    pX8: { paddingHorizontal: 32 };
    pX10: { paddingHorizontal: 40 };
    pX12: { paddingHorizontal: 48 };
    pX16: { paddingHorizontal: 64 };
    pX20: { paddingHorizontal: 80 };
    pX24: { paddingHorizontal: 96 };
    pX32: { paddingHorizontal: 128 };
    pX40: { paddingHorizontal: 160 };
    pX48: { paddingHorizontal: 192 };
    pX56: { paddingHorizontal: 224 };
    pX64: { paddingHorizontal: 256 };
    pXPx: { paddingHorizontal: 1 };
    pY0: { paddingVertical: 0 };
    pY1: { paddingVertical: 4 };
    pY2: { paddingVertical: 8 };
    pY3: { paddingVertical: 12 };
    pY4: { paddingVertical: 16 };
    pY5: { paddingVertical: 20 };
    pY6: { paddingVertical: 24 };
    pY8: { paddingVertical: 32 };
    pY10: { paddingVertical: 40 };
    pY12: { paddingVertical: 48 };
    pY16: { paddingVertical: 64 };
    pY20: { paddingVertical: 80 };
    pY24: { paddingVertical: 96 };
    pY32: { paddingVertical: 128 };
    pY40: { paddingVertical: 160 };
    pY48: { paddingVertical: 192 };
    pY56: { paddingVertical: 224 };
    pY64: { paddingVertical: 256 };
    pYPx: { paddingVertical: 1 };
    pT0: { paddingTop: 0 };
    pT1: { paddingTop: 4 };
    pT2: { paddingTop: 8 };
    pT3: { paddingTop: 12 };
    pT4: { paddingTop: 16 };
    pT5: { paddingTop: 20 };
    pT6: { paddingTop: 24 };
    pT8: { paddingTop: 32 };
    pT10: { paddingTop: 40 };
    pT12: { paddingTop: 48 };
    pT16: { paddingTop: 64 };
    pT20: { paddingTop: 80 };
    pT24: { paddingTop: 96 };
    pT32: { paddingTop: 128 };
    pT40: { paddingTop: 160 };
    pT48: { paddingTop: 192 };
    pT56: { paddingTop: 224 };
    pT64: { paddingTop: 256 };
    pTPx: { paddingTop: 1 };
    pR0: { paddingRight: 0 };
    pR1: { paddingRight: 4 };
    pR2: { paddingRight: 8 };
    pR3: { paddingRight: 12 };
    pR4: { paddingRight: 16 };
    pR5: { paddingRight: 20 };
    pR6: { paddingRight: 24 };
    pR8: { paddingRight: 32 };
    pR10: { paddingRight: 40 };
    pR12: { paddingRight: 48 };
    pR16: { paddingRight: 64 };
    pR20: { paddingRight: 80 };
    pR24: { paddingRight: 96 };
    pR32: { paddingRight: 128 };
    pR40: { paddingRight: 160 };
    pR48: { paddingRight: 192 };
    pR56: { paddingRight: 224 };
    pR64: { paddingRight: 256 };
    pRPx: { paddingRight: 1 };
    pB0: { paddingBottom: 0 };
    pB1: { paddingBottom: 4 };
    pB2: { paddingBottom: 8 };
    pB3: { paddingBottom: 12 };
    pB4: { paddingBottom: 16 };
    pB5: { paddingBottom: 20 };
    pB6: { paddingBottom: 24 };
    pB8: { paddingBottom: 32 };
    pB10: { paddingBottom: 40 };
    pB12: { paddingBottom: 48 };
    pB16: { paddingBottom: 64 };
    pB20: { paddingBottom: 80 };
    pB24: { paddingBottom: 96 };
    pB32: { paddingBottom: 128 };
    pB40: { paddingBottom: 160 };
    pB48: { paddingBottom: 192 };
    pB56: { paddingBottom: 224 };
    pB64: { paddingBottom: 256 };
    pBPx: { paddingBottom: 1 };
    pL0: { paddingLeft: 0 };
    pL1: { paddingLeft: 4 };
    pL2: { paddingLeft: 8 };
    pL3: { paddingLeft: 12 };
    pL4: { paddingLeft: 16 };
    pL5: { paddingLeft: 20 };
    pL6: { paddingLeft: 24 };
    pL8: { paddingLeft: 32 };
    pL10: { paddingLeft: 40 };
    pL12: { paddingLeft: 48 };
    pL16: { paddingLeft: 64 };
    pL20: { paddingLeft: 80 };
    pL24: { paddingLeft: 96 };
    pL32: { paddingLeft: 128 };
    pL40: { paddingLeft: 160 };
    pL48: { paddingLeft: 192 };
    pL56: { paddingLeft: 224 };
    pL64: { paddingLeft: 256 };
    pLPx: { paddingLeft: 1 };
    pS0: { paddingStart: 0 };
    pS1: { paddingStart: 4 };
    pS2: { paddingStart: 8 };
    pS3: { paddingStart: 12 };
    pS4: { paddingStart: 16 };
    pS5: { paddingStart: 20 };
    pS6: { paddingStart: 24 };
    pS8: { paddingStart: 32 };
    pS10: { paddingStart: 40 };
    pS12: { paddingStart: 48 };
    pS16: { paddingStart: 64 };
    pS20: { paddingStart: 80 };
    pS24: { paddingStart: 96 };
    pS32: { paddingStart: 128 };
    pS40: { paddingStart: 160 };
    pS48: { paddingStart: 192 };
    pS56: { paddingStart: 224 };
    pS64: { paddingStart: 256 };
    pSPx: { paddingStart: 1 };
    pE0: { paddingEnd: 0 };
    pE1: { paddingEnd: 4 };
    pE2: { paddingEnd: 8 };
    pE3: { paddingEnd: 12 };
    pE4: { paddingEnd: 16 };
    pE5: { paddingEnd: 20 };
    pE6: { paddingEnd: 24 };
    pE8: { paddingEnd: 32 };
    pE10: { paddingEnd: 40 };
    pE12: { paddingEnd: 48 };
    pE16: { paddingEnd: 64 };
    pE20: { paddingEnd: 80 };
    pE24: { paddingEnd: 96 };
    pE32: { paddingEnd: 128 };
    pE40: { paddingEnd: 160 };
    pE48: { paddingEnd: 192 };
    pE56: { paddingEnd: 224 };
    pE64: { paddingEnd: 256 };
    pEPx: { paddingEnd: 1 };
    textTransparent: { color: 'rgba(0,0,0,0)' };
    textBlack: { color: '#000' };
    textWhite: { color: '#fff' };
    textGray100: { color: '#eee' };
    textGray200: { color: '#ebebeb' };
    textGray300: { color: '#ececec' };
    textGray400: { color: '#ccc' };
    textGray500: { color: '#999' };
    textGray600: { color: '#777' };
    textGray700: { color: '#555' };
    textGray800: { color: '#1a1a1a' };
    textGray900: { color: '#111' };
    textBlueLighter: { color: '#99ffff' };
    textBlueLight: { color: '#99ccff' };
    textBlue: { color: 'blue' };
    textGreen: { color: '#00cc66' };
    textOrange: { color: '#ff9900' };
    textPink: { color: '#ff9999' };
    textPinkIntense: { color: '#ff00cc' };
    textPurple: { color: '#6633cc' };
    textRedLighter: { color: '#ff3366' };
    textRedLight: { color: '#ff0066' };
    textRed: { color: '#ff0033' };
    textTealLight: { color: '#99ff99' };
    textTeal: { color: '#00ffcc' };
    textYellow: { color: '#ffce33' };
    tintTransparent: { tintColor: 'rgba(0,0,0,0)' };
    tintBlack: { tintColor: '#000' };
    tintWhite: { tintColor: '#fff' };
    tintGray100: { tintColor: '#eee' };
    tintGray200: { tintColor: '#ebebeb' };
    tintGray300: { tintColor: '#ececec' };
    tintGray400: { tintColor: '#ccc' };
    tintGray500: { tintColor: '#999' };
    tintGray600: { tintColor: '#777' };
    tintGray700: { tintColor: '#555' };
    tintGray800: { tintColor: '#1a1a1a' };
    tintGray900: { tintColor: '#111' };
    tintBlueLighter: { tintColor: '#99ffff' };
    tintBlueLight: { tintColor: '#99ccff' };
    tintBlue: { tintColor: 'blue' };
    tintGreen: { tintColor: '#00cc66' };
    tintOrange: { tintColor: '#ff9900' };
    tintPink: { tintColor: '#ff9999' };
    tintPinkIntense: { tintColor: '#ff00cc' };
    tintPurple: { tintColor: '#6633cc' };
    tintRedLighter: { tintColor: '#ff3366' };
    tintRedLight: { tintColor: '#ff0066' };
    tintRed: { tintColor: '#ff0033' };
    tintTealLight: { tintColor: '#99ff99' };
    tintTeal: { tintColor: '#00ffcc' };
    tintYellow: { tintColor: '#ffce33' };
    w0: { width: 0 };
    w1: { width: 4 };
    w2: { width: 8 };
    w3: { width: 12 };
    w4: { width: 16 };
    w5: { width: 20 };
    w6: { width: 24 };
    w8: { width: 32 };
    w10: { width: 40 };
    w12: { width: 48 };
    w16: { width: 64 };
    w20: { width: 80 };
    w24: { width: 96 };
    w32: { width: 128 };
    w40: { width: 160 };
    w48: { width: 192 };
    w56: { width: 224 };
    w64: { width: 256 };
    wAuto: { width: 'auto' };
    wPx: { width: 1 };
    w1_2: { width: '50%' };
    w1_3: { width: '33.333333%' };
    w2_3: { width: '66.666667%' };
    w1_4: { width: '25%' };
    w2_4: { width: '50%' };
    w3_4: { width: '75%' };
    w1_5: { width: '20%' };
    w2_5: { width: '40%' };
    w3_5: { width: '60%' };
    w4_5: { width: '80%' };
    w1_6: { width: '16.666667%' };
    w2_6: { width: '33.333333%' };
    w3_6: { width: '50%' };
    w4_6: { width: '66.666667%' };
    w5_6: { width: '83.333333%' };
    w1_12: { width: '8.333333%' };
    w2_12: { width: '16.666667%' };
    w3_12: { width: '25%' };
    w4_12: { width: '33.333333%' };
    w5_12: { width: '41.666667%' };
    w6_12: { width: '50%' };
    w7_12: { width: '58.333333%' };
    w8_12: { width: '66.666667%' };
    w9_12: { width: '75%' };
    w10_12: { width: '83.333333%' };
    w11_12: { width: '91.666667%' };
    wFull: { width: '100%' };
    wScreen: { width: '100vw' };
    z0: { zIndex: 0 };
    z10: { zIndex: 10 };
    z20: { zIndex: 20 };
    z30: { zIndex: 30 };
    z40: { zIndex: 40 };
    z50: { zIndex: 50 };
    zAuto: { zIndex: 0 };
    shadow: { shadowColor: 'rgba(0, 0, 0, 0.1)'; shadowOffset: {'width':0,'height':1}; shadowRadius: 3; shadowOpacity: 1; elevation: 1.5 };
    shadowMd: { shadowColor: 'rgba(0, 0, 0, 0.1)'; shadowOffset: {'width':0,'height':4}; shadowRadius: 6; shadowOpacity: 1; elevation: 3 };
    shadowLg: { shadowColor: 'rgba(0, 0, 0, 0.1)'; shadowOffset: {'width':0,'height':10}; shadowRadius: 15; shadowOpacity: 1; elevation: 7.5 };
    shadowXl: { shadowColor: 'rgba(0, 0, 0, 0.1)'; shadowOffset: {'width':0,'height':20}; shadowRadius: 25; shadowOpacity: 1; elevation: 12.5 };
    shadow2xl: { shadowColor: 'rgba(0, 0, 0, 0.25)'; shadowOffset: {'width':0,'height':25}; shadowRadius: 50; shadowOpacity: 1; elevation: 25 };
    shadowInner: { shadowColor: 'rgba(0, 0, 0, 0)'; shadowOffset: {'width':0,'height':0}; shadowRadius: 0; shadowOpacity: 0; elevation: 0 };
    shadowOutline: { shadowColor: 'rgba(66, 153, 225, 0.5)'; shadowOffset: {'width':0,'height':0}; shadowRadius: 0; shadowOpacity: 1; elevation: 0 };
    shadowNone: { shadowColor: 'rgba(0, 0, 0, 0)'; shadowOffset: {'width':0,'height':0}; shadowRadius: 0; shadowOpacity: 0; elevation: 0 };
    textShadow: { textShadowColor: 'rgba(0, 0, 0, 0.1)'; textShadowOffset: {'width':0,'height':1}; textShadowRadius: 3 };
    textShadowMd: { textShadowColor: 'rgba(0, 0, 0, 0.1)'; textShadowOffset: {'width':0,'height':4}; textShadowRadius: 6 };
    textShadowLg: { textShadowColor: 'rgba(0, 0, 0, 0.1)'; textShadowOffset: {'width':0,'height':10}; textShadowRadius: 15 };
    textShadowXl: { textShadowColor: 'rgba(0, 0, 0, 0.1)'; textShadowOffset: {'width':0,'height':20}; textShadowRadius: 25 };
    textShadow2xl: { textShadowColor: 'rgba(0, 0, 0, 0.25)'; textShadowOffset: {'width':0,'height':25}; textShadowRadius: 50 };
    textShadowInner: { textShadowColor: 'rgba(0, 0, 0, 0)'; textShadowOffset: {'width':0,'height':0}; textShadowRadius: 0 };
    textShadowOutline: { textShadowColor: 'rgba(66, 153, 225, 0.5)'; textShadowOffset: {'width':0,'height':0}; textShadowRadius: 0 };
    textShadowNone: { textShadowColor: 'rgba(0, 0, 0, 0)'; textShadowOffset: {'width':0,'height':0}; textShadowRadius: 0 };
    insetDir0: { top: 0; bottom: 0; start: 0; end: 0 };
    insetDirAuto: { top: 'auto'; bottom: 'auto'; start: 'auto'; end: 'auto' };
    insetDirX0: { start: 0; end: 0 };
    insetDirXAuto: { start: 'auto'; end: 'auto' };
    borderDir0: { borderWidth: 0 };
    borderDir2: { borderWidth: 2 };
    borderDir4: { borderWidth: 4 };
    borderDir8: { borderWidth: 8 };
    borderDir: { borderWidth: 1 };
    borderDirX0: { borderEndWidth: 0; borderStartWidth: 0 };
    borderDirX2: { borderEndWidth: 2; borderStartWidth: 2 };
    borderDirX4: { borderEndWidth: 4; borderStartWidth: 4 };
    borderDirX8: { borderEndWidth: 8; borderStartWidth: 8 };
    borderDirX: { borderEndWidth: 1; borderStartWidth: 1 };
    borderDirE0: { borderEndWidth: 0 };
    borderDirE2: { borderEndWidth: 2 };
    borderDirE4: { borderEndWidth: 4 };
    borderDirE8: { borderEndWidth: 8 };
    borderDirE: { borderEndWidth: 1 };
    borderDirS0: { borderStartWidth: 0 };
    borderDirS2: { borderStartWidth: 2 };
    borderDirS4: { borderStartWidth: 4 };
    borderDirS8: { borderStartWidth: 8 };
    borderDirS: { borderStartWidth: 1 };
    roundedDirNone: { borderRadius: 0 };
    roundedDirSm: { borderRadius: 2 };
    roundedDir: { borderRadius: 4 };
    roundedDirLg: { borderRadius: 8 };
    roundedDirFull: { borderRadius: 9999 };
    roundedDirENone: { borderTopEndRadius: 0; borderBottomEndRadius: 0 };
    roundedDirESm: { borderTopEndRadius: 2; borderBottomEndRadius: 2 };
    roundedDirE: { borderTopEndRadius: 4; borderBottomEndRadius: 4 };
    roundedDirELg: { borderTopEndRadius: 8; borderBottomEndRadius: 8 };
    roundedDirEFull: { borderTopEndRadius: 9999; borderBottomEndRadius: 9999 };
    roundedDirSNone: { borderTopStartRadius: 0; borderBottomStartRadius: 0 };
    roundedDirSSm: { borderTopStartRadius: 2; borderBottomStartRadius: 2 };
    roundedDirS: { borderTopStartRadius: 4; borderBottomStartRadius: 4 };
    roundedDirSLg: { borderTopStartRadius: 8; borderBottomStartRadius: 8 };
    roundedDirSFull: { borderTopStartRadius: 9999; borderBottomStartRadius: 9999 };
    roundedDirTsNone: { borderTopStartRadius: 0 };
    roundedDirTsSm: { borderTopStartRadius: 2 };
    roundedDirTs: { borderTopStartRadius: 4 };
    roundedDirTsLg: { borderTopStartRadius: 8 };
    roundedDirTsFull: { borderTopStartRadius: 9999 };
    roundedDirTeNone: { borderTopEndRadius: 0 };
    roundedDirTeSm: { borderTopEndRadius: 2 };
    roundedDirTe: { borderTopEndRadius: 4 };
    roundedDirTeLg: { borderTopEndRadius: 8 };
    roundedDirTeFull: { borderTopEndRadius: 9999 };
    roundedDirBeNone: { borderBottomEndRadius: 0 };
    roundedDirBeSm: { borderBottomEndRadius: 2 };
    roundedDirBe: { borderBottomEndRadius: 4 };
    roundedDirBeLg: { borderBottomEndRadius: 8 };
    roundedDirBeFull: { borderBottomEndRadius: 9999 };
    roundedDirBsNone: { borderBottomStartRadius: 0 };
    roundedDirBsSm: { borderBottomStartRadius: 2 };
    roundedDirBs: { borderBottomStartRadius: 4 };
    roundedDirBsLg: { borderBottomStartRadius: 8 };
    roundedDirBsFull: { borderBottomStartRadius: 9999 };
  }

  export const color: TailwindColors;
  export const colors: TailwindColors;
  export const t: TailwindStyles;
  export const tailwind: TailwindStyles;
  export const theme: TailwindStyles;
  export const tw: TailwindStyles;
}